import { api } from '../api/client';
import { supabase } from '../../lib/supabase';
import { RANTECH_WORKSPACE_ID } from '../../domain/workspace/constants';
import type { Lead } from '../../domain/leads/types';

export interface LeadsRepository { list(): Promise<Lead[]>; getById(id: string): Promise<Lead | undefined>; create(input: Partial<Lead>): Promise<Lead>; update(id: string, input: Partial<Lead>): Promise<Lead>; }

type LeadRow = { id: string; company: string; owner: string; city: string; segment: string; stage: Lead['stage']; score: number; priority: Lead['priority']; website: string; phone: string | null; whatsapp: string | null; instagram_url: string | null; source: string | null; source_url: string | null; recommended_service: string; secondary_service: string | null; diagnosis: string; pain_points: string[]; opportunities: string[]; recommended_demo: string; next_action: string; objections: string[]; commercial_memory: string; history: Lead['history']; workspace_id: string; created_at: string; updated_at: string; };

function toLead(row: LeadRow): Lead { return { id: row.id, company: row.company, owner: row.owner, city: row.city, segment: row.segment as Lead['segment'], stage: row.stage, score: row.score, priority: row.priority, website: row.website, lastActivity: row.updated_at, nextAction: row.next_action, painPoints: row.pain_points ?? [], opportunities: row.opportunities ?? [], recommendedService: row.recommended_service, recommendedDemo: row.recommended_demo, diagnosis: row.diagnosis, objections: row.objections ?? [], commercialMemory: row.commercial_memory, history: row.history ?? [] }; }

function toRow(input: Partial<Lead>) { return { ...(input.company !== undefined && { company: input.company }), ...(input.owner !== undefined && { owner: input.owner }), ...(input.city !== undefined && { city: input.city }), ...(input.segment !== undefined && { segment: input.segment }), ...(input.stage !== undefined && { stage: input.stage }), ...(input.score !== undefined && { score: input.score }), ...(input.priority !== undefined && { priority: input.priority }), ...(input.website !== undefined && { website: input.website }), ...(input.nextAction !== undefined && { next_action: input.nextAction }), ...(input.painPoints !== undefined && { pain_points: input.painPoints }), ...(input.opportunities !== undefined && { opportunities: input.opportunities }), ...(input.recommendedService !== undefined && { recommended_service: input.recommendedService }), ...(input.recommendedDemo !== undefined && { recommended_demo: input.recommendedDemo }), ...(input.diagnosis !== undefined && { diagnosis: input.diagnosis }), ...(input.objections !== undefined && { objections: input.objections }), ...(input.commercialMemory !== undefined && { commercial_memory: input.commercialMemory }), ...(input.history !== undefined && { history: input.history }) }; }

const mswRepository: LeadsRepository = { list: () => api<Lead[]>('/api/leads'), getById: async id => { try { return await api<Lead>(`/api/leads/${id}`); } catch { return undefined; } }, create: input => api<Lead>('/api/leads', { method: 'POST', body: JSON.stringify(input) }), update: (id, input) => api<Lead>(`/api/leads/${id}`, { method: 'PATCH', body: JSON.stringify(input) }) };

const supabaseRepository: LeadsRepository = { async list() { if (!RANTECH_WORKSPACE_ID) throw new Error('Workspace RanTech não configurado.'); const { data, error } = await supabase.from('li_leads').select('*').eq('workspace_id', RANTECH_WORKSPACE_ID).order('updated_at', { ascending: false }); if (error) throw error; return (data as LeadRow[]).map(toLead); }, async getById(id) { if (!RANTECH_WORKSPACE_ID) throw new Error('Workspace RanTech não configurado.'); const { data, error } = await supabase.from('li_leads').select('*').eq('workspace_id', RANTECH_WORKSPACE_ID).eq('id', id).maybeSingle(); if (error) throw error; return data ? toLead(data as LeadRow) : undefined; }, async create(input) { if (!RANTECH_WORKSPACE_ID) throw new Error('Workspace RanTech não configurado.'); const { data, error } = await supabase.from('li_leads').insert({ ...toRow(input), workspace_id: RANTECH_WORKSPACE_ID }).select('*').single(); if (error) throw error; return toLead(data as LeadRow); }, async update(id, input) { if (!RANTECH_WORKSPACE_ID) throw new Error('Workspace RanTech não configurado.'); const { data, error } = await supabase.from('li_leads').update(toRow(input)).eq('workspace_id', RANTECH_WORKSPACE_ID).eq('id', id).select('*').single(); if (error) throw error; return toLead(data as LeadRow); } };

const useSupabase = import.meta.env.VITE_DATA_SOURCE === 'supabase' && import.meta.env.MODE !== 'test';
export const leadsRepository: LeadsRepository = useSupabase ? supabaseRepository : mswRepository;
