-- Marco C: isolated workspace-scoped Lead Intelligence schema.
-- Existing public.leads/public.pipeline tables are intentionally untouched.
create table if not exists public.li_workspaces (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.li_workspace_members (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('admin','member')), created_at timestamptz not null default now(), unique(workspace_id,user_id));
insert into public.li_workspaces (id,name,slug) values ('00000000-0000-0000-0000-000000000001','RanTech','rantech') on conflict (slug) do nothing;
create table if not exists public.li_leads (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, company text not null check (char_length(company) between 2 and 160), owner text not null default 'RanTech', city text not null default '', segment text not null, stage text not null default 'Novo', score smallint not null default 0 check (score between 0 and 100), priority text not null default 'Baixa', website text not null default '', phone text, whatsapp text, instagram_url text, source text, source_url text, recommended_service text not null default '', secondary_service text, diagnosis text not null default '', pain_points text[] not null default '{}', opportunities text[] not null default '{}', recommended_demo text not null default '', next_action text not null default '', objections text[] not null default '{}', commercial_memory text not null default '', history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint li_leads_stage_check check (stage in ('Novo','Analisando','Qualificado','Contato preparado','Contatado','Respondeu','Interessado','Demonstração','Negociação','Fechado','Sem resposta','Não interessado','Adiado','Perdido','Reativação futura')));
create table if not exists public.li_lead_analysis (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade unique, digital_diagnosis text not null default '', pain_points text[] not null default '{}', commercial_opportunities text[] not null default '{}', score_rationale text, signals jsonb not null default '{}'::jsonb, observations text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.li_lead_events (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, event_type text not null, title text not null, description text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), created_by uuid references auth.users(id));
create table if not exists public.li_lead_contacts (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, channel text not null, direction text not null, summary text not null, result text, contacted_at timestamptz not null default now(), follow_up_at timestamptz, metadata jsonb not null default '{}'::jsonb);
create table if not exists public.li_lead_objections (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, objection text not null, context text, created_at timestamptz not null default now());
create table if not exists public.li_lead_scores (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, score smallint not null check (score between 0 and 100), components jsonb not null default '{}'::jsonb, rationale text, rules_version text not null default 'v1', calculated_at timestamptz not null default now());
create table if not exists public.li_demos (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, name text not null, niche text not null, niche_family text not null, demo_type text not null check (demo_type in ('visual_example','personalized_demo','pdf_demo')), related_service text not null, description text not null default '', thumbnail_url text, destination_url text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.li_lead_demos (workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, demo_id uuid not null references public.li_demos(id) on delete cascade, relation text not null default 'recommended', created_at timestamptz not null default now(), primary key (lead_id,demo_id));
create table if not exists public.li_followups (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.li_workspaces(id) on delete cascade, lead_id uuid not null references public.li_leads(id) on delete cascade, planned_at timestamptz, action text not null, status text not null default 'planned', reason text, completed_at timestamptz, result text, created_at timestamptz not null default now());

do $$ declare t text; begin foreach t in array array['li_workspaces','li_workspace_members','li_leads','li_lead_analysis','li_lead_events','li_lead_contacts','li_lead_objections','li_lead_scores','li_demos','li_lead_demos','li_followups'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
create policy li_workspace_members_select on public.li_workspace_members for select to authenticated using (user_id=(select auth.uid()) or exists(select 1 from public.li_workspace_members m where m.workspace_id=li_workspace_members.workspace_id and m.user_id=(select auth.uid()) and m.role='admin'));
create policy li_workspace_members_admin_write on public.li_workspace_members for all to authenticated using (exists(select 1 from public.li_workspace_members m where m.workspace_id=li_workspace_members.workspace_id and m.user_id=(select auth.uid()) and m.role='admin')) with check (exists(select 1 from public.li_workspace_members m where m.workspace_id=li_workspace_members.workspace_id and m.user_id=(select auth.uid()) and m.role='admin'));
do $$ declare t text; begin foreach t in array array['li_leads','li_lead_analysis','li_lead_events','li_lead_contacts','li_lead_objections','li_lead_scores','li_demos','li_lead_demos','li_followups'] loop execute format('create policy %I on public.%I for select to authenticated using (exists(select 1 from public.li_workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid())))',t||'_select',t,t); execute format('create policy %I on public.%I for insert to authenticated with check (exists(select 1 from public.li_workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid())))',t||'_insert',t,t); execute format('create policy %I on public.%I for update to authenticated using (exists(select 1 from public.li_workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid()))) with check (exists(select 1 from public.li_workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid())))',t||'_update',t,t,t); execute format('create policy %I on public.%I for delete to authenticated using (exists(select 1 from public.li_workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid())))',t||'_delete',t,t); end loop; end $$;
