import type { Lead } from "./types";
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    company: "Oficina Torque Norte",
    owner: "Equipe RanTech",
    city: "São Paulo, SP",
    segment: "Oficina & mecânica",
    stage: "Interessado",
    score: 94,
    priority: "Alta",
    website: "Sem site",
    lastActivity: "Hoje, 09:12",
    nextAction: "Enviar proposta de landing + agendamento",
    painPoints: [
      "Não aparece no Google Maps",
      "Atendimento depende do WhatsApp",
    ],
    opportunities: ["SEO local", "Orçamento online", "Prova social"],
    recommendedService: "Landing page de conversão",
    recommendedDemo: "Demo Oficina Torque",
    diagnosis:
      "Negócio forte no bairro, mas invisível na busca local e sem uma jornada clara para solicitar orçamento.",
    objections: ["“Já tenho Instagram”"],
    commercialMemory:
      "Dono valoriza objetividade e quer reduzir chamadas fora do horário.",
    history: [
      {
        date: "Hoje",
        title: "Resposta recebida",
        note: "Pediu para ver um exemplo de página.",
      },
      {
        date: "Ontem",
        title: "Contato inicial",
        note: "Mensagem enviada com diagnóstico rápido.",
      },
    ],
  },
  {
    id: "lead-002",
    company: "Barbearia Navalha 13",
    owner: "Rafael Lima",
    city: "Curitiba, PR",
    segment: "Barbearia & beleza",
    stage: "Demonstração",
    score: 87,
    priority: "Alta",
    website: "navalha13.com.br",
    lastActivity: "Ontem, 16:40",
    nextAction: "Personalizar demo com identidade da Navalha 13",
    painPoints: ["Site desatualizado", "Agendamento fragmentado"],
    opportunities: [
      "Página de serviços",
      "Agenda integrada",
      "Campanhas sazonais",
    ],
    recommendedService: "Site institucional + agenda",
    recommendedDemo: "Demo Navalha 13",
    diagnosis:
      "A marca é lembrada, mas o digital não traduz a experiência premium da loja.",
    objections: ["Prazo de implementação"],
    commercialMemory:
      "Busca uma solução que pareça premium e seja simples de manter.",
    history: [
      {
        date: "Ontem",
        title: "Demo aberta",
        note: "Visualizou a tela de serviços por 3 minutos.",
      },
    ],
  },
  {
    id: "lead-003",
    company: "Auto Elétrica Fênix",
    owner: "Caio Mendes",
    city: "Campinas, SP",
    segment: "Oficina & mecânica",
    stage: "Qualificado",
    score: 78,
    priority: "Média",
    website: "autoeletricafenix.com",
    lastActivity: "2 dias atrás",
    nextAction: "Validar ticket médio e região atendida",
    painPoints: ["Poucas avaliações recentes"],
    opportunities: ["Campanha de avaliações", "Páginas por serviço"],
    recommendedService: "Otimização de presença local",
    recommendedDemo: "Demo Oficina Torque",
    diagnosis:
      "Já existe uma base digital, mas falta transformar intenção em contato.",
    objections: ["“Vou pensar”"],
    commercialMemory: "Lead técnico; responder com dados e antes/depois.",
    history: [],
  },
  {
    id: "lead-004",
    company: "Studio Aura Pilates",
    owner: "Equipe RanTech",
    city: "Belo Horizonte, MG",
    segment: "Nicho emergente",
    stage: "Analisando",
    score: 71,
    priority: "Média",
    website: "Instagram apenas",
    lastActivity: "3 dias atrás",
    nextAction: "Concluir diagnóstico de presença digital",
    painPoints: ["Dependência de indicação"],
    opportunities: ["Landing de aula experimental", "Captação de leads"],
    recommendedService: "Landing page de campanha",
    recommendedDemo: "Demo Studio Aura",
    diagnosis: "Serviço de alto valor e baixa descoberta orgânica.",
    objections: [],
    commercialMemory:
      "Ainda não houve contato; oportunidade para abordagem consultiva.",
    history: [],
  },
  {
    id: "lead-005",
    company: "Clínica Vet Bairro Alto",
    owner: "Rafael Lima",
    city: "Porto Alegre, RS",
    segment: "Nicho emergente",
    stage: "Contato preparado",
    score: 63,
    priority: "Baixa",
    website: "clinicavetbairroalto.com.br",
    lastActivity: "5 dias atrás",
    nextAction: "Enviar abordagem com foco em plantão",
    painPoints: ["Informação de emergência difícil de achar"],
    opportunities: ["Página de plantão", "SEO por intenção"],
    recommendedService: "Site de serviço local",
    recommendedDemo: "Demo Clínica Vet",
    diagnosis:
      "A urgência do cliente pede uma experiência clara e rápida no celular.",
    objections: ["Orçamento do trimestre"],
    commercialMemory: "Priorizar o ganho de clareza, não volume de páginas.",
    history: [],
  },
  {
    id: "lead-006",
    company: "Brilho Garage",
    owner: "Caio Mendes",
    city: "Santos, SP",
    segment: "Oficina & mecânica",
    stage: "Novo",
    score: 82,
    priority: "Alta",
    website: "Instagram apenas",
    lastActivity: "Hoje, 08:45",
    nextAction: "Mapear serviços mais buscados",
    painPoints: ["Baixa descoberta local"],
    opportunities: ["Estética automotiva", "Página de serviços"],
    recommendedService: "Landing page de conversão",
    recommendedDemo: "Demo Brilho Garage",
    diagnosis: "Serviço visual com forte potencial de prova antes/depois.",
    objections: [],
    commercialMemory: "",
    history: [],
  },
  {
    id: "lead-007",
    company: "Ponto Fino Barbearia",
    owner: "Rafael Lima",
    city: "Recife, PE",
    segment: "Barbearia & beleza",
    stage: "Sem resposta",
    score: 58,
    priority: "Baixa",
    website: "pontofino.com.br",
    lastActivity: "7 dias atrás",
    nextAction: "Reativar em 14 dias",
    painPoints: ["Agendamento por mensagens"],
    opportunities: ["Agenda online"],
    recommendedService: "Site institucional + agenda",
    recommendedDemo: "Demo Navalha 13",
    diagnosis: "Marca local com jornada digital fragmentada.",
    objections: [],
    commercialMemory: "Reativação futura com nova abordagem.",
    history: [],
  },
  {
    id: "lead-008",
    company: "Casa Lume Arquitetura",
    owner: "Equipe RanTech",
    city: "Florianópolis, SC",
    segment: "Nicho emergente",
    stage: "Novo",
    score: 69,
    priority: "Média",
    website: "Instagram apenas",
    lastActivity: "Hoje, 07:30",
    nextAction: "Enviar diagnóstico de portfólio",
    painPoints: ["Portfólio difícil de navegar"],
    opportunities: ["Landing de captação", "Cases organizados"],
    recommendedService: "Landing page de campanha",
    recommendedDemo: "Demo Studio Aura",
    diagnosis:
      "Serviço consultivo que precisa transformar repertório em confiança.",
    objections: [],
    commercialMemory: "",
    history: [],
  },
];
